### ISSUE TITLE
mixing translated questions ? (error ?)

### ISSUE THREAD

**Issue by BlackBrix** [ron4mac/joomla_plg_qa#1]
Hi,  
I created a german translation   
and put it in the newly created folder "../plugins/captcha/qa/language/de-DE"  
  
I just copied all files from  "../plugins/captcha/qa/language/en-GB"  
into the new folder "../plugins/captcha/qa/language/de-DE" and renamed the 3 files to:  
de-DE.custom.ini.sample  
de-DE.plg_captcha_qa.ini  
de-DE.plg_captcha_qa.sys.ini  
  
then I started to translate the file "de-DE.plg_captcha_qa.ini" only.
then I wantet to implement my own german Q's and A's and created a new set of   
Variables PLG_CAPTCHA_QA_Q1 to PLG_CAPTCHA_QA_Q7  
I deleted PLG_CAPTCHA_QA_Q8, PLG_CAPTCHA_QA_Q9 within the file "de-DE.plg_captcha_qa.ini" planning to add more and more questions later.  
  
Now the error happens, that a german website-user sometimes sees the english questions PLG_CAPTCHA_QA_Q8,   PLG_CAPTCHA_QA_Q9 from the english translation...  
  
Can some file be modificated, that only german questions appear to a german site user ?  
no matter how much german questions are in the german file de-DE.plg_captcha_qa.ini" ...  
  
What happens if I have more german questions than english questions ?  
e.g. PLG_CAPTCHA_QA_Q1 ... PLG_CAPTCHA_QA_Q25  
  
is it only working correctly if I have exactly the same no. of questions in the english and in the german file ?  
  
or is the Number of questions limited to 9 generally (hardcoded) ?

**Comment by ron4mac** [comment]
As currently designed, there must be exactly 9 questions/answers. If more work is ever done on this plugin, that is an area that will receive some attention.
