### ISSUE TITLE
wish: no matter if lowercase / uppercase in the answers

### ISSUE THREAD

**Issue by BlackBrix** [ron4mac/joomla_plg_qa#2]
if the correct answer is a (german) word,
it would be nice if it would not matter if the user types an answer in uppercase / lowercase chars ...
maybe one could implement a 'strtolower' somewhere before compairing the users answer in the php file ?

**Comment by ron4mac** [comment]
It is possible in some q/a, that case insensitive would not be desirable. Each question can have multiple acceptable answers where case could be different.
