### ISSUE TITLE
usable even in Joomla 4

### ISSUE THREAD

**Issue by BlackBrix** [ron4mac/joomla_plg_qa#3]
when exchanging the SetError() Method to the newer enqueueMessage() Method,
this plugin runs on Joomla 3 and even on joomla 4  ...   ;-)
-> https://github.com/BlackBrix/joomla_plg_qa/commit/95eafde3f6a1cbf86f6e5dfabe798aa73f1f1dcd

**Comment by ron4mac** [comment]
Thank you ...

**Comment by ron4mac** [comment]
Made changes similar to yours
