### ISSUE TITLE
Label doesn't translate into another language

### ISSUE THREAD

**Issue by Gitjk** [ron4mac/joomla_plg_qa#4]
Hi,
I've tested your plugin in a Joomla 4 test-installation. Works nicely, except that the language key/string:
`PLG_CAPTCHA_QA_LABEL_PLEASE="To protect our site from spam, please answer a simple question."`
isn't loaded when I add for example a de-DE.plg_captcha_qa.ini.
All other language keys/strings do translate.

Greetings

Joerg

**Comment by Gitjk** [comment]
Here is a translation into German
[de-DE.plg_captcha_qa.ini.zip](https://github.com/ron4mac/joomla_plg_qa/files/8693946/de-DE.plg_captcha_qa.ini.zip)

**Comment by ron4mac** [comment]
That language string definition is also in the custom.ini file and may be overriding.
Thank you for the German translation.
