### ISSUE TITLE
update fails

### ISSUE THREAD

**Issue by BlackBrix** [ron4mac/joomla_plg_qa#5]
in the joomla backend it is showing, that an update from 1.4 to 1.4.1 is available
referring to the XML https://rjcrans.net/jupdates/plg_qa/updates.xml

the update fails with the message that I can / shall manually download & install from:
"https://rjcrans.net/jupdates/plg_qa/plg_captcha_qa_1.4.1.zip"
this URL is taken from the XML (see above)

when trying to download manually from "https://rjcrans.net/jupdates/plg_qa/plg_captcha_qa_1.4.1.zip"
I get an error "The requested URL was not found on this server."

**Comment by ron4mac** [comment]
Apologies ...
Corrected.
